In [4]:
import pandas as pd


In [5]:
titanic_train =pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",sep='\t')
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [3]:
#description try to give you small statistical ananlysis of data like mean. Only for numrical data 

titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [8]:
#Filter data types which has data type is object

titanic_train.dtypes[titanic_train.dtypes=="object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [9]:
#Extract data having dtype is object

t=titanic_train[titanic_train.dtypes[titanic_train.dtypes=="object"].index]
t

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female   
152                                   Meo, Mr. Alfonzo    male   
153                    van Billiard, Mr. Austin Blyler    male   
154                              Olsen, Mr. Ole Martin    male   
155                        Williams, Mr. Charles Duane    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
151            113776    C2        S  
152        A.5. 11206   NaN        S  
153          A/5. 851   NaN        S  
154         Fa 265302   NaN        S  
155          PC 17597   NaN        C  

[156 rows x 5 columns]

In [6]:
#series datatype work as list

type(titanic_train['Pclass'])

pandas.core.series.Series

In [7]:
#slicing in list

titanic_train['Pclass'][5:0:-1]

5    3
4    3
3    1
2    3
1    1
Name: Pclass, dtype: int64

In [8]:
#create new column

titanic_train["sudh"]="kumar"

In [9]:
#total category of data in dataset

pd.Categorical(titanic_train['Pclass'])

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [13]:
#to check null value

(titanic_train['Age'].isnull()==True)

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [16]:
#filter rows having age =NULL
import numpy as np

np.where(titanic_train['Age'].isnull()==True)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [20]:
#to find maximum fare

np.where(titanic_train['Fare']==max(titanic_train['Fare']))

(array([27, 88], dtype=int64),)

In [22]:
 #Extract rows

titanic_train.iloc[[1,2]]

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked   sudh  
1      0          PC 17599  71.2833   C85        C  kumar  
2      0  STON/O2. 3101282   7.9250   NaN        S  kumar

In [23]:
#extract rows having max fare

titanic_train.iloc[np.where(titanic_train['Fare']==max(titanic_train['Fare']))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare        Cabin Embarked   sudh  
27  19.0      3      2  19950  263.0  C23 C25 C27        S  kumar  
88  23.0      3      2  19950  263.0  C23 C25 C27        S  kumar

In [25]:
#names of people have survived

titanic_train.iloc[np.where(titanic_train['Survived']==1)]['Name']

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
8      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                    Nasser, Mrs. Nicholas (Adele Achem)
10                       Sandstrom, Miss. Marguerite Rut
11                              Bonnell, Miss. Elizabeth
15                      Hewlett, Mrs. (Mary D Kingcome) 
17                          Williams, Mr. Charles Eugene
19                               Masselmani, Mrs. Fatima
21                                 Beesley, Mr. Lawrence
22                           McGowan, Miss. Anna "Annie"
23                          Sloper, Mr. William Thompson
25     Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
28                         O'Dwyer, Miss. Ellen "Nellie"
31        Spencer, Mrs. William Augustus (Marie Eugenie)
32                              Glynn, Miss. Mary Agatha
36                             

In [3]:
#Convert into series
import numpy as np
lables=['a','b','c','d']
list_1= [12,45,67]
array=np.array(list_1)
d={'a':34,"b":20}

In [6]:
#Conversion with predeifined index 
import pandas as pd

pd.Series(list_1,index=["a","b","c"])

a    12
b    45
c    67
dtype: int64

In [7]:
pd.Series(array)

0    12
1    45
2    67
dtype: int32

In [9]:
#Dictionary to series, Key become index 

pd.Series(d)

a    34
b    20
dtype: int64

In [11]:
#Create dummy series. Name index can be repative. But Numerical index is unique

s1=pd.Series([1,2,3,4],index=['a','b','c','d'])

In [12]:
#Get data from first index a

s1[0]

1

In [13]:
#Loc location

s1.loc['a']

1

In [14]:
#Random data is genertated

from numpy.random import randn as rn

In [15]:
rn(5,5)

array([[-0.25925487, -0.32859068, -0.12355743,  0.0212492 ,  1.03711098],
       [-1.13259112,  1.00080183,  0.51564316,  0.90376049, -1.11194799],
       [-1.04864043, -0.97158411,  0.97063201,  0.65499986,  2.0521285 ],
       [-1.25886746,  0.95899741,  0.1014454 , -0.05090667,  0.10117621],
       [ 0.02471356, -1.69653419, -0.21083849, -0.90594353,  1.11686925]])

In [17]:
pd.DataFrame(rn(5,5))

0         1         2         3         4
0 -0.012216  1.006339 -1.295154 -0.611838 -1.706462
1  0.007703  1.560967 -1.077769  0.914219  0.975227
2  2.342892  0.470404  1.278948 -0.987518  0.268948
3  1.597003 -0.174677 -0.574852  0.551621 -0.195579
4  1.393033 -1.163272 -1.133332  0.223771 -0.897704

In [23]:
#Rename column

df=pd.DataFrame(rn(5,5), index=['a','b','c','d','e'],columns=['Alpha','Beta',"gamma",'Delta',"phie"])

In [25]:
df

Alpha      Beta     gamma     Delta      phie
a  1.637874 -0.654234 -0.447284 -1.877780  0.488543
b -1.010488  0.144099  1.112466  0.108703  1.411571
c  0.380210  2.857243  0.241737  0.494155  1.134836
d -0.678234  0.893803 -0.475421  0.784419  0.459962
e -0.321658  1.762596  0.484020 -0.224973  0.446235

In [26]:
df.iloc[[0,3]]

Alpha      Beta     gamma     Delta      phie
a  1.637874 -0.654234 -0.447284 -1.877780  0.488543
d -0.678234  0.893803 -0.475421  0.784419  0.459962

In [27]:
df.loc[['a','d']]

Alpha      Beta     gamma     Delta      phie
a  1.637874 -0.654234 -0.447284 -1.877780  0.488543
d -0.678234  0.893803 -0.475421  0.784419  0.459962

In [30]:
#Create new column

df['new_column']=df['Alpha']*df['Beta']
df

Alpha      Beta     gamma     Delta      phie  new_column
a  1.637874 -0.654234 -0.447284 -1.877780  0.488543   -1.071553
b -1.010488  0.144099  1.112466  0.108703  1.411571   -0.145610
c  0.380210  2.857243  0.241737  0.494155  1.134836    1.086351
d -0.678234  0.893803 -0.475421  0.784419  0.459962   -0.606207
e -0.321658  1.762596  0.484020 -0.224973  0.446235   -0.566954

In [32]:
#Drop column

df.drop({'a','c'})

Alpha      Beta     gamma     Delta      phie  new_column
b -1.010488  0.144099  1.112466  0.108703  1.411571   -0.145610
d -0.678234  0.893803 -0.475421  0.784419  0.459962   -0.606207
e -0.321658  1.762596  0.484020 -0.224973  0.446235   -0.566954

In [38]:
#Delete specific record 

df.iloc[0:2,0:3]

Alpha      Beta     gamma
a  1.637874 -0.654234 -0.447284
b -1.010488  0.144099  1.112466

In [40]:
df>0

Alpha   Beta  gamma  Delta  phie  new_column
a   True  False  False  False  True       False
b  False   True   True   True  True       False
c   True   True   True   True  True        True
d  False   True  False   True  True       False
e  False   True   True  False  True       False

In [42]:
#Extract dataset having gamma value is negative

df[df['gamma']<0]

Alpha      Beta     gamma     Delta      phie  new_column
a  1.637874 -0.654234 -0.447284 -1.877780  0.488543   -1.071553
d -0.678234  0.893803 -0.475421  0.784419  0.459962   -0.606207

In [44]:
#reset index

df.reset_index()

index     Alpha      Beta     gamma     Delta      phie  new_column
0     a  1.637874 -0.654234 -0.447284 -1.877780  0.488543   -1.071553
1     b -1.010488  0.144099  1.112466  0.108703  1.411571   -0.145610
2     c  0.380210  2.857243  0.241737  0.494155  1.134836    1.086351
3     d -0.678234  0.893803 -0.475421  0.784419  0.459962   -0.606207
4     e -0.321658  1.762596  0.484020 -0.224973  0.446235   -0.566954

In [46]:
#Modify any column as index 

df.set_index('gamma')

Alpha      Beta     Delta      phie  new_column
gamma                                                        
-0.447284  1.637874 -0.654234 -1.877780  0.488543   -1.071553
 1.112466 -1.010488  0.144099  0.108703  1.411571   -0.145610
 0.241737  0.380210  2.857243  0.494155  1.134836    1.086351
-0.475421 -0.678234  0.893803  0.784419  0.459962   -0.606207
 0.484020 -0.321658  1.762596 -0.224973  0.446235   -0.566954