In [3]:
import numpy as np

In [3]:
a= np.array([1,2,3,4,5,6])

In [4]:
type(a)

numpy.ndarray

In [7]:
#ndarray = N dimentional data 

np.array([1,2,3,4,5,"sudh"])

array(['1', '2', '3', '4', '5', 'sudh'], dtype='<U11')

In [8]:
#6 dimension array

np.array([1,1300],ndmin=6)

array([[[[[[   1, 1300]]]]]])

In [3]:
#String array

np.array([5,6,7],dtype=str)

array(['5', '6', '7'], dtype='<U1')

In [4]:
np.asarray([4,5,6])

array([4, 5, 6])

In [5]:
#array into float

np.asarray([4,5,6,7],dtype=np.float16)

array([4., 5., 6., 7.], dtype=float16)

In [6]:
#Matrix

mat=np.matrix([5,6])
mat

matrix([[5, 6]])

In [7]:
#If dataset is already availbe in any form of arrray . No conversion

np.asanyarray(mat)

matrix([[5, 6]])

In [8]:
#list into arrya

l=[1,2,3,4]
np.asanyarray(l)

array([1, 2, 3, 4])

In [11]:
#allow to generate array from your condition

np.fromfunction(lambda i,j:i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [12]:
np.fromfunction(lambda i,j:i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [14]:
np.fromfunction(lambda i,j:i**i, (3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [4., 4., 4.]])

In [21]:
#used to convert into integer from string array, seperator is =' '

np.fromstring("24 25",sep=' ')

array([24., 25.])

In [22]:
np.fromstring("4,6",sep=',')

array([4., 6.])

In [4]:
a1=np.array([5,6,7,8])

In [5]:
a2=np.array([5,6,7,8,9])

In [26]:
a3=np.array([[5,6,11,8],[2,8,9]])

<ipython-input-26-791b4a1b4a24>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a3=np.array([[5,6,11,8],[2,8,9]])


In [27]:
#Find a dimension using ndim

a2.ndim

1

In [28]:
#size: total no of element

a1.size

4

In [7]:
#Shape: No of row & column

a1.shape

(4,)

In [10]:
#List of tuple by default conversion

np.array([(2,3,4,5),(2,8,9,11)])

array([[ 2,  3,  4,  5],
       [ 2,  8,  9, 11]])

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
#random number using ARANGE

np.arange(0,5.6,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4])

In [16]:
#Linspace generate 50 data between 2 & 5 

np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [18]:
np.linspace(0,9,num=20)

array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.89473684,
       2.36842105, 2.84210526, 3.31578947, 3.78947368, 4.26315789,
       4.73684211, 5.21052632, 5.68421053, 6.15789474, 6.63157895,
       7.10526316, 7.57894737, 8.05263158, 8.52631579, 9.        ])

In [20]:
#NA Array

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#NA 3D array

np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.empty((2,2))

array([[2.12199579e-314, 1.04189993e-311],
       [1.60077269e-321, 2.22809558e-312]])

In [26]:
#Identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#Reshape array

np.arange(16).reshape((1,16))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [29]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
np.random.rand(2,3)

array([[0.82031952, 0.73375921, 0.35328307],
       [0.31240691, 0.62853851, 0.32487003]])

In [31]:
np.random.randn(4,5)

array([[ 0.26639819,  2.20283394,  0.20212294,  0.09388888, -0.29076889],
       [-0.60154788, -1.07074611,  0.13297967,  1.09666498,  0.18036178],
       [ 0.52497147, -2.28143047, -0.44758004,  0.65585157,  1.16395263],
       [-0.84794812,  0.10705727,  0.91026221, -0.04538303, -1.22386455]])

In [33]:
#RAndom number betwen 1 to 5 . With matrxi 4x3

np.random.randint(1,5,(4,3))

array([[1, 4, 1],
       [2, 2, 4],
       [1, 3, 4],
       [4, 4, 4]])

In [36]:
a5=np.random.randint(2,6,(3,6))
a5

array([[4, 4, 3, 4, 3, 5],
       [5, 2, 4, 3, 5, 3],
       [3, 5, 4, 3, 5, 5]])

In [37]:
np.sort(a5)

array([[3, 3, 4, 4, 4, 5],
       [2, 3, 3, 4, 5, 5],
       [3, 3, 4, 5, 5, 5]])

In [38]:
#sort by row wise 

np.sort(a5,axis=1)

array([[3, 3, 4, 4, 4, 5],
       [2, 3, 3, 4, 5, 5],
       [3, 3, 4, 5, 5, 5]])

In [40]:
a6 =np.random.randint(2,10,(3,3))
a6

array([[5, 5, 8],
       [9, 6, 8],
       [5, 4, 5]])

a6

In [43]:
#start from second row and go till first column 

a6[2:1]

array([], shape=(0, 3), dtype=int32)

In [44]:
a7=np.random.randint(3,7,(6,6))

In [45]:
#Interaction of row and column

a7[2:5,2:4]

array([[4, 3],
       [3, 3],
       [5, 6]])

In [46]:
#Matrix Multiplication 

a6@a7

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 3)

In [47]:
a7 ** 3

array([[125,  27,  64,  64, 216, 125],
       [ 64,  27, 216,  27, 216, 125],
       [216, 125,  64,  27, 216,  64],
       [216, 125,  27,  27,  64,  64],
       [216, 216, 125, 216,  27, 125],
       [ 64,  64,  27, 125, 216, 125]], dtype=int32)

In [ ]:
5